let ingredients = [
    {
        id: 1,
        name: "Potato",
        bgColor: "#f0e68c",
        categoria: "Vegetable",
        affinità: ["Onion", "Garlic", "Rosemary", "Butter", "Salt"],
        isBlackListed: false,
        isVegan: true,
        isGlutenFree: true,
        isVegetarian: true,
        isSelected: false,
    },
    {
        id: 2,
        name: "Tomato",
        bgColor: "#ff6347",
        categoria: "Vegetable",
        affinità: ["Basil", "Mozzarella", "Olive oil", "Garlic", "Salt"],
        isBlackListed: false,
        isVegan: true,
        isGlutenFree: true,
        isVegetarian: true,
        isSelected: false,
    },
    {
        id: 3,
        name: "Onion",
        bgColor: "#9370db",
        categoria: "Vegetable",
        affinità: ["Garlic", "Thyme", "Olive oil", "Beef", "Salt"],
        isBlackListed: false,
        isVegan: true,
        isGlutenFree: true,
        isVegetarian: true,
        isSelected: false,
    },
    {
        id: 4,
        name: "Garlic",
        bgColor: "#d3d3d3",
        categoria: "Vegetable",
        affinità: ["Onion", "Rosemary", "Olive oil", "Tomato", "Lemon"],
        isBlackListed: false,
        isVegan: true,
        isGlutenFree: true,
        isVegetarian: true,
        isSelected: false,
    },
    {
        id: 5,
        name: "Rosemary",
        bgColor: "#6b8e23",
        categoria: "Herb",
        affinità: ["Potato", "Garlic", "Olive oil", "Lemon", "Chicken"],
        isBlackListed: false,
        isVegan: true,
        isGlutenFree: true,
        isVegetarian: true,
        isSelected: false,
    },
    {
        id: 6,
        name: "Butter",
        bgColor: "#ffd700",
        categoria: "Dairy",
        affinità: ["Potato", "Tomato", "Mozzarella", "Basil", "Pasta"],
        isBlackListed: false,
        isVegan: false,
        isGlutenFree: true,
        isVegetarian: true,
        isSelected: false,
    },
    {
        id: 7,
        name: "Basil",
        bgColor: "#228b22",
        categoria: "Herb",
        affinità: ["Tomato", "Mozzarella", "Olive oil", "Garlic", "Pasta"],
        isBlackListed: false,
        isVegan: true,
        isGlutenFree: true,
        isVegetarian: true,
        isSelected: false,
    },
    {
        id: 8,
        name: "Mozzarella",
        bgColor: "#fffafa",
        categoria: "Dairy",
        affinità: ["Tomato", "Basil", "Olive oil", "Pasta", "Pizza"],
        isBlackListed: false,
        isVegan: false,
        isGlutenFree: true,
        isVegetarian: true,
        isSelected: false,
    },
    {
        id: 9,
        name: "Olive oil",
        bgColor: "#808000",
        categoria: "Oil",
        affinità: ["Tomato", "Basil", "Garlic", "Lemon", "Pasta"],
        isBlackListed: false,
        isVegan: true,
        isGlutenFree: true,
        isVegetarian: true,
        isSelected: false,
    },
    {
        id: 10,
        name: "Salt",
        bgColor: "#ffffff",
        categoria: "Seasoning",
        affinità: ["Potato", "Tomato", "Onion", "Garlic", "Lemon"],
        isBlackListed: false,
        isVegan: true,
        isGlutenFree: true,
        isVegetarian: true,
        isSelected: false,
    },
    {
        id: 11,
        name: "Beef",
        bgColor: "#8b4513",
        categoria: "Meat",
        affinità: ["Onion", "Garlic", "Thyme", "Rosemary", "Potato"],
        isBlackListed: false,
        isVegan: false,
        isGlutenFree: true,
        isVegetarian: false,
        isSelected: false,
    },
    {
        id: 13,
        name: "Parmesan cheese",
        bgColor: "#f4a460",
        categoria: "Dairy",
        affinità: ["Garlic", "Lemon", "Broccoli", "Mozzarella", "Pasta"],
        isBlackListed: false,
        isVegan: false,
        isGlutenFree: true,
        isVegetarian: true,
        isSelected: false,
    },
    {
        id: 14,
        name: "Chicken",
        bgColor: "#ff8c00",
        categoria: "Meat",
        affinità: ["Garlic", "Lemon", "Olive oil", "Thyme", "Pasta"],
        isBlackListed: false,
        isVegan: false,
        isGlutenFree: true,
        isVegetarian: false,
        isSelected: false,
    },
    {
        id: 15,
        name: "Fish",
        bgColor: "#4682b4",
        categoria: "Seafood",
        affinità: ["Garlic", "Lemon", "Olive oil", "Pasta", "Broccoli"],
        isBlackListed: false,
        isVegan: false,
        isGlutenFree: true,
        isVegetarian: false,
        isSelected: false,
    },
    {
        id: 16,
        name: "Pasta",
        bgColor: "#ff0000",
        categoria: "Grain",
        affinità: ["Garlic", "Lemon", "Olive oil", "Parmesan cheese", "Chicken"],
        isBlackListed: false,
        isVegan: true,
        isGlutenFree: false,
        isVegetarian: true,
        isSelected: false,
    },
    {
        id: 17,
        name: "Oregano",
        bgColor: "#00ff00",
        categoria: "Herb",
        affinità: ["Tomato", "Mozzarella", "Basil", "Olive oil", "Pasta"],
        isBlackListed: false,
        isVegan: true,
        isGlutenFree: true,
        isVegetarian: true,
        isSelected: false,
    },
    {
        id: 18,
        name: "Salmon",
        bgColor: "#ffdfa3",
        categoria: "Fish",
        affinità: ["Dill", "Lemon", "Honey", "Soy sauce", "Garlic"],
        isBlackListed: false,
        isVegan: false,
        isGlutenFree: true,
        isVegetarian: false,
        isSelected: false,
    },
    {
        id: 19,
        name: "Lettuce",
        bgColor: "#ff00ff",
        categoria: "Vegetable",
        affinità: ["Tomato", "Cucumber", "Carrot", "Olive oil", "Vinegar"],
        isBlackListed: false,
        isVegan: true,
        isGlutenFree: true,
        isVegetarian: true,
        isSelected: false,
    },
    {
        id: 20,
        name: "Vinegar",
        bgColor: "#ffff00",
        categoria: "Condiment",
        affinità: ["Lettuce", "Tomato", "Cucumber", "Olive oil", "Salt"],
        isBlackListed: false,
        isVegan: true,
        isGlutenFree: true,
        isVegetarian: true,
        isSelected: false,
    },
    {
        id: 21,
        name: "Cucumber",
        bgColor: "#00ffff",
        categoria: "Vegetable",
        affinità: ["Tomato", "Lettuce", "Carrot", "Olive oil", "Vinegar"],
        isBlackListed: false,
        isVegan: true,
        isGlutenFree: true,
        isVegetarian: true,
        isSelected: false,
    },
    {
        id: 22,
        name: "Carrot",
        bgColor: "#ff4500",
        categoria: "Vegetable",
        affinità: ["Lettuce", "Cucumber", "Tomato", "Olive oil", "Vinegar"],
        isBlackListed: false,
        isVegan: true,
        isGlutenFree: true,
        isVegetarian: true,
        isSelected: false,
    },
    {
        id: 23,
        name: "Red pepper",
        bgColor: "#ff8c00",
        categoria: "Vegetable",
        affinità: ["Onion", "Garlic", "Olive oil", "Salt", "Black pepper"],
        isBlackListed: false,
        isVegan: true,
        isGlutenFree: true,
        isVegetarian: true,
        isSelected: false,
    },
    {
        id: 48,
        name: "Broccoli",
        bgColor: "#7cfc00",
        categoria: "Vegetable",
        affinità: ["Garlic", "Lemon", "Parmesan cheese", "Olive oil", "Salt"],
        isBlackListed: false,
        isVegan: true,
        isGlutenFree: true,
        isVegetarian: true,
        isSelected: false,
    },
    // Ingredienti dopo il 48 rimangono come nel tuo esempio
    {
        id: 49,
        name: "Lemon",
        bgColor: "#fffacd",
        categoria: "Fruit",
        affinità: ["Garlic", "Butter", "Chicken", "Fish", "Pasta"],
        isBlackListed: false,
        isVegan: true,
        isGlutenFree: true,
        isVegetarian: true,
        isSelected: false,
    },
    {
        id: 50,
        name: "Zucchini",
        bgColor: "#98fb98",
        categoria: "Vegetable",
        affinità: ["Garlic", "Parmesan cheese", "Basil", "Olive oil", "Lemon"],
        isBlackListed: false,
        isVegan: true,
        isGlutenFree: true,
        isVegetarian: true,
        isSelected: false,
    },
]

export default ingredients
